name: build
on: push

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "12"
        cache: 'npm'
    - run: npm ci

    - run: npm run env:setup
    - run: npm run linux:build

    - uses: actions/upload-artifact@v2
      with:
        name: linux-app
        path: |
          out/linux/Jasper
